// examples/schnorr_example.rs

use std::sync::Arc;

/// Example: Simple Schnorr proofs using Spongefish
///
/// Schnorr proofs prove knowledge of a secret key over a group G of prime order p
/// where the discrete logarithm problem is hard.
///
/// Protocol flow:
/// 1. Setup: Define interaction pattern
/// 2. P → V: Statement (generator G, public key X)
/// 3. P → V: K (commitment - a group element)
/// 4. V → P: c (challenge - a scalar, generated from transcript)
/// 5. P → V: r (response - a scalar)
/// 6. V: Check P * r == K + X * c
use ark_ec::{CurveGroup, PrimeGroup};
use ark_std::UniformRand;
use rand::rngs::OsRng;
use spongefish::{
    codecs::arkworks_algebra::{
        FieldPattern,
        GroupPattern,
        // Extension traits for ergonomic API
        ProverFieldMessageExt,
        ProverGroupMessageExt,
        UnitToField,
        VerifierFieldMessageExt,
        VerifierGroupMessageExt,
    },
    codecs::unit::Pattern as _,
    pattern::{InteractionPattern, Label, PatternState},
    DefaultHash, ProofError, ProofResult, ProverState, VerifierState,
};

/// Create the interaction pattern for Schnorr protocol
fn schnorr_pattern<G: CurveGroup>() -> InteractionPattern {
    let mut pattern = PatternState::new();
    pattern
        .message_points::<G>(Label::from("generator"), 1)
        .message_points::<G>(Label::from("public_key"), 1)
        .ratchet()
        .message_points::<G>(Label::from("commitment"), 1)
        .challenge_scalars::<G::ScalarField>(Label::from("challenge"), 1)
        .message_scalars::<G::ScalarField>(Label::from("response"), 1);

    pattern.finalize().expect("Failed to finalize pattern")
}

/// Key generation: returns (secret_key, public_key)
fn keygen<G: PrimeGroup>() -> (G::ScalarField, G) {
    let sk = G::ScalarField::rand(&mut OsRng);
    let pk = G::generator() * sk;
    (sk, pk)
}

/// Schnorr proof generation
#[allow(non_snake_case)]
fn prove<G, R>(
    prover: &mut ProverState<DefaultHash, u8, R>,
    P: G,
    x: G::ScalarField,
) -> ProofResult<()>
where
    G: CurveGroup,
    R: rand::RngCore + rand::CryptoRng,
    ProverState<DefaultHash, u8, R>: ProverGroupMessageExt<G>
        + ProverFieldMessageExt<G::ScalarField>
        + UnitToField<G::ScalarField>,
{
    // Generate random nonce
    let k = G::ScalarField::rand(prover.rng().unwrap());
    let K = P * k;

    // Send commitment
    prover.message_points(Label::from("commitment"), &[K]);

    // Get challenge from transcript (Fiat-Shamir)
    let mut c_buf = [G::ScalarField::default(); 1];
    prover.fill_challenge_scalars(Label::from("challenge"), &mut c_buf);
    let c = c_buf[0];

    // Compute and send response
    let r = k + c * x;
    prover.message_scalars(Label::from("response"), &[r]);

    Ok(())
}

/// Schnorr proof verification
#[allow(non_snake_case)]
fn verify<G>(verifier: &mut VerifierState<DefaultHash, u8>, P: G, X: G) -> ProofResult<()>
where
    G: CurveGroup,
    for<'a> VerifierState<'a, DefaultHash, u8>: VerifierGroupMessageExt<G>
        + VerifierFieldMessageExt<G::ScalarField>
        + UnitToField<G::ScalarField>,
{
    // Read commitment
    let mut K_buf = [G::default(); 1];
    verifier.fill_message_points(Label::from("commitment"), &mut K_buf);
    let K = K_buf[0];

    // Generate challenge from transcript (same as prover via Fiat-Shamir)
    let mut c_buf = [G::ScalarField::default(); 1];
    verifier.fill_challenge_scalars(Label::from("challenge"), &mut c_buf);
    let c = c_buf[0];

    // Read response
    let mut r_buf = [G::ScalarField::default(); 1];
    verifier.fill_message_scalars(Label::from("response"), &mut r_buf);
    let r = r_buf[0];

    // Verify: P * r == K + X * c
    if P * r == K + X * c {
        Ok(())
    } else {
        Err(ProofError::InvalidProof)
    }
}

fn main() {
    println!("=== Schnorr Proof Example ===\n");

    // Choose elliptic curve group (Curve25519)
    type G = ark_curve25519::EdwardsProjective;

    // Step 1: Create and finalize the interaction pattern
    let pattern = Arc::new(schnorr_pattern::<G>());
    println!("✓ Pattern created and finalized");

    // Step 2: Setup - generate keys
    #[allow(non_snake_case)]
    let P = G::generator();
    #[allow(non_snake_case)]
    let (x, X) = keygen::<G>();
    println!("✓ Keys generated\n");

    // Step 3: Prover generates proof
    let proof = {
        let mut prover = ProverState::new(pattern.clone(), OsRng);

        // Send statement (generator and public key)
        prover
            .message_points(Label::from("generator"), &[P])
            .message_points(Label::from("public_key"), &[X])
            .ratchet();

        // Generate and send proof
        prove(&mut prover, P, x).expect("Prove failed");

        prover.finalize()
    };

    let proof = match proof {
        Ok(p) => {
            println!("✓ Proof generated by prover");
            p
        }
        Err(e) => {
            println!("✗ Proving failed: {:?}", e);
            std::process::exit(1);
        }
    };

    // Step 4: Verifier checks proof
    let result = {
        let mut verifier = VerifierState::new(pattern.clone(), &proof);

        // Read statement
        let mut generator = [G::default(); 1];
        let mut public_key = [G::default(); 1];
        verifier
            .fill_message_points(Label::from("generator"), &mut generator)
            .fill_message_points(Label::from("public_key"), &mut public_key)
            .ratchet();

        println!("✓ Statement read by verifier");

        // Verify the proof
        verify(&mut verifier, generator[0], public_key[0]).expect("Verification failed");

        verifier.finalize()
    };

    match result {
        Ok(()) => {
            println!("✓ Proof verified successfully!");
            println!("  The prover knows the secret key for the public key");
        }
        Err(e) => {
            println!("✗ Verification failed: {:?}", e);
            std::process::exit(1);
        }
    }
}
